# FIXME: This list doesn't specify what ports/protocols should be opened.

variable "cidr_blocks_extra" {
  description = "Optional list of CIDR blocks"
  type        = list(string)
  default     = []
}

variable "name_prefix" {
  description = "Prefix to prepend to autogenerated security group names"
  default     = null
}

variable "client_sg_name" {
  description = "Client security group name"
  default     = null
}

variable "server_sg_name" {
  description = "Server security group name"
  default     = null
}

variable "rules" {
  description = "Security group rule(s) by protocol and port"
  # TODO: Validate that there are no unexpected values.
  type = object({
    icmp = optional(list(number), [])
    tcp  = optional(list(number), [])
    udp  = optional(list(number), [])
  })

  # Validate subnet_type (if specified).

  validation {
    condition     = length(concat(var.rules.icmp, var.rules.tcp, var.rules.udp)) > 0
    error_message = "At least one protocol ('icmp', 'tcp', or 'udp') with a list of one or more ports is required."
  }
}

variable "tags" {
  description = "Tags to be applied to resources where supported"
  type        = map(string)
  default     = {}
}

variable "vpc" {
  description = "VPC name"
}

# Debugging.

variable "_debug" {
  description = "Produce debug output (boolean)"
  type        = bool
  default     = false
}
